<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>svg</title>-->
<!--    <link rel="stylesheet" href="../public/assets/css/style.css">-->
<!---->
<!--</head>-->
<!--<body>-->
<!--<h1>Avatar</h1>-->
<!---->
<!--<div>-->
<!--    --><?//=$avatar;?>
<!--</div>-->
<!---->
<!--<p>Nom du fichier :--><?//=$filename;?><!-- </p>-->
<!---->
<!--<a href="../libs/save.php?filename=--><?//=$filename;?><!--">Sauvegarder</a>-->
<!--</body>-->